#!/usr/bin/env python3
#
# Copyright 2026 AUTOMATOUS.IO
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
"""
Build flash-ready artifacts for one model in one command.

    python3 scripts/build.py shelly-1-gen4
    -> automatous-io-shelly-1-gen4-esphome-v1.0.0-ota.zip      (stock web UI OTA)
    -> automatous-io-shelly-1-gen4-esphome-v1.0.0-uart.bin     (UART/esptool full-flash image)

Picks the model config (configs/<model>.yaml), wraps it with the stock partition layout
in a generated .installer-<model>.yaml, compiles it with ESPHome, and packages the build
via make-esphome-ota-zip.py. The wrapper exists because the model yamls must stay free
of local file references (like the custom partition CSV) to keep working as remote packages
for dashboard adoption.

Run with no arguments to list buildable models. Needs the ESPHome venv active
(see README).
"""
import argparse
import importlib.util
import json
import re
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ESPHOME_DIR = ROOT / "configs"
PARTITIONS = "../partitions/shelly-gen4-stock.csv"

INSTALLER_TEMPLATE = """\
# Generated by scripts/build.py — local build wrapper, not for remote import.
packages:
  config: !include {model}.yaml

# Overrides the base's static project version; the firmware reports the same
# version as the artifact filenames. Adopted/remote builds keep the base's value.
esphome:
  project:
    version: "{version}"

esp32:
  partitions: {partitions}
"""


def load_zipper():
    path = Path(__file__).with_name("make-esphome-ota-zip.py")
    spec = importlib.util.spec_from_file_location("make_esphome_ota_zip", path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def make_merged_bin(zipper, build_dir, out_path):
    """One image with everything at its real offset, for esptool/UART flashing at 0x0.

    Offsets come from the build's flasher_args.json; file names go through the zipper's
    CANDIDATES because PlatformIO renames the bins flasher_args.json points at.
    """
    flasher = json.loads((build_dir / "flasher_args.json").read_text())
    chip = flasher["extra_esptool_args"]["chip"]
    args = []
    for role in ("bootloader", "partition-table", "otadata", "app"):
        path = zipper.find(str(build_dir), zipper.CANDIDATES[role])
        if not path:
            sys.exit(f"merged bin: no {role} image in {build_dir}")
        args += [flasher[role]["offset"], path]
    for merge_cmd in ("merge-bin", "merge_bin"):  # esptool v5 / v4 spelling
        if subprocess.run([sys.executable, "-m", "esptool", "--chip", chip,
                           merge_cmd, "-o", str(out_path), *args]).returncode == 0:
            print(f"Created {out_path.name} ({out_path.stat().st_size / 1024 / 1024:.1f} MB) — "
                  f"UART full-flash image: esptool --chip {chip} write-flash 0x0 {out_path.name}")
            return
    sys.exit("esptool merge-bin failed")


def list_models(hardware):
    print("models (hardware codes from make-esphome-ota-zip.py):")
    for hw in sorted(hardware):
        status = "ready" if (ESPHOME_DIR / f"{hw}.yaml").is_file() else "no config yet — PRs welcome"
        print(f"  {hw:22} {status}")


def main():
    zipper = load_zipper()
    hardware = zipper.HARDWARE
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("model", nargs="?", choices=sorted(hardware),
                        help="Shelly model to build (omit to list)")
    parser.add_argument("--version", default="1.0.0",
                        help="version stamped into the zip name (default 1.0.0)")
    args = parser.parse_args()

    if not args.model:
        list_models(hardware)
        return

    model_yaml = ESPHOME_DIR / f"{args.model}.yaml"
    if not model_yaml.is_file():
        sys.exit(f"{model_yaml} does not exist — add the model config first (see README)")
    if not shutil.which("esphome"):
        sys.exit("esphome not on PATH — activate the venv first: source ~/esphome-venv/bin/activate")

    installer = ESPHOME_DIR / f".installer-{args.model}.yaml"
    installer.write_text(INSTALLER_TEMPLATE.format(
        model=args.model, partitions=PARTITIONS, version=args.version))

    if subprocess.run(["esphome", "compile", installer.name], cwd=ESPHOME_DIR).returncode:
        sys.exit("esphome compile failed")

    m = re.search(r'^\s*device_name:\s*"?([A-Za-z0-9_-]+)"?', model_yaml.read_text(), re.M)
    device_name = m.group(1) if m else args.model
    build_root = ESPHOME_DIR / ".esphome" / "build" / device_name
    candidates = [build_root / ".pioenvs" / device_name,  # PlatformIO layout (<= 2026.3)
                  build_root / "build"]                   # direct esp-idf layout (2026.4+)
    build_dir = next((d for d in candidates if (d / "flasher_args.json").is_file()), None)
    if not build_dir:
        sys.exit(f"no build output under {build_root} — expected one of: "
                 + ", ".join(str(d) for d in candidates))

    zipper_script = Path(__file__).with_name("make-esphome-ota-zip.py")
    if subprocess.run([sys.executable, str(zipper_script),
                       "--hardware", args.model, "--version", args.version,
                       "--build-dir", str(build_dir)], cwd=ROOT).returncode:
        sys.exit("zip packaging failed")

    make_merged_bin(zipper, build_dir,
                    ROOT / f"automatous-io-{args.model}-esphome-v{args.version}-uart.bin")


if __name__ == "__main__":
    main()
